language:
- node_js

node_js:
- 12

env:
- DATABASE_URL=postgresql://postgres@localhost:5432/my_waiters

before_script:
 - psql -c 'create database my_waiters;' -U postgres
 - psql -U postgres -d my_waiters -a -f table.sql

services:
- postgresql